import type { Metadata } from "next";
import "./globals.css";
import { Geist, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/components/header";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const neuePlak = localFont({
  src: "./fonts/neuePlak.ttf",
  variable: "--font-neue-plak",
});

const basis33 = localFont({
  src: "./fonts/basis33.ttf",
  variable: "--font-basis33",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${neuePlak.variable} ${basis33.variable} ${montserrat.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
